### PR TITLE
Added file streams

### PR DESCRIPTION
**Pull request by lockie**
Hey! :wave:
Here's the PR I was talking about in #35. Let me know if there's something I can improve here.

### CODE REVIEW

**Comment by resttime** [comment]
If you can throw a quick example into the examples folder I think it'll be
perfect. It can be simple like reading a txt file thrown in there too.

**Comment by lockie** [comment]
Done! :ok_hand:

**Comment by resttime** [comment]
Merged in, the contribution is much appreciated

**Comment by lockie** [comment]
Awesome, thank you! :blush:

**Pull request merged**
